Repository boostcampwm-2024/refactor-iOS03-SniffMeet, pull requests merged in 2025-01, with the labels that each got.

#8 [fix] 중복된 Compile Sources 파일 제거
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
Labels: bug

#4 [refactor] persistance layer 추상화 리팩토링
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Router/ProfileCreateRouter.swift
  SniffMeet/SniffMeet/Source/Home/EditProfile/Router/ProfileEditRoutable.swift
  SniffMeet/SniffMeet/Source/Home/Main/HomeModuleBuilder.swift
  SniffMeet/SniffMeet/Source/Persistence/CacheManager.swift
  SniffMeet/SniffMeet/Source/Persistence/DataStoragable.swift
  SniffMeet/SniffMeet/Source/Persistence/KeychainManager.swift
  SniffMeet/SniffMeet/Source/Persistence/SNMFileManager.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/LoadUserInfoUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/RegisterDeviceTokenUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/RemoteSaveDeviceTokenUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/SaveUserInfoUseCase.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Router/RequestWalkRouter.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Router/RespondWalkRouter.swift
Labels: refactor

#6 [refactor] 에러 타입 정리
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/App/SNMError.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Interactor/ProfileCreateInteractor.swift
  SniffMeet/SniffMeet/Source/Common/Util/SNMLogger.swift
  SniffMeet/SniffMeet/Source/Supabase/Auth/SupabaseAuthManager.swift
  SniffMeet/SniffMeet/Source/Supabase/Auth/SupabaseAuthRequest.swift
  SniffMeet/SniffMeet/Source/Supabase/Database/SupabaseDatabaseManager.swift
  SniffMeet/SniffMeet/Source/Supabase/Storage/SupabaseStorageManager.swift
  SniffMeet/SniffMeet/Source/Supabase/SupabaseError.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestUserInfoRemoteUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RespondUseCase/RespondMateRequestUseCase.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Interactor/ProcessedWalkInteractor.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Interactor/RespondWalkInteractor.swift
Labels: refactor

#9 [fix] Test 파일과 Target 수정
  SniffMeet/SNMPersistenceTests/FileManagerTest.swift
  SniffMeet/SNMPersistenceTests/KeychainTests.swift
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
Labels: bug, refactor

#14 [test] 코드 커버리지 측정 환경 설정
  SniffMeet/SNMPersistenceTests/FileManagerTest.swift
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet.xcodeproj/xcshareddata/xcschemes/SniffMeet.xcscheme
  SniffMeet/SupabaseTests/SupabaseStorageTests.swift
  SniffMeet/TestPlan/SNMNetworkTestPlan.xctestplan
  SniffMeet/TestPlan/SNMPersistenceTestPlan.xctestplan
  SniffMeet/TestPlan/SNMTestplan.xctestplan
  SniffMeet/TestPlan/SupabaseTestPlan.xctestplan
Labels: test

#23 [ refactor] 캐시 정책 시간복잡도 개선
  SniffMeet/SNMPersistenceTests/FileManagerTest.swift
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SniffMeet/SniffMeet/Source/Mate/MateList/Router/MateListRouter.swift
  SniffMeet/SniffMeet/Source/Persistence/CacheManager.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestProfileImageUseCase.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Router/RequestWalkRouter.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Router/ProcessedWalkRouter.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Router/RespondWalkRouter.swift
Labels: refactor

#27 [refactor] 프로필 등록 시점에 멀티스레딩 적용
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Interactor/ProfileCreateInteractor.swift
Labels: refactor

#24 [Feature, Refactor] 이미지 다운샘플링 적용, 프로필/썸네일 이미지 분리
  SniffMeet/SNMUtilityTests/ImageSamplingTests.swift
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet.xcodeproj/xcshareddata/xcschemes/SNMNetworkTests.xcscheme
  SniffMeet/SniffMeet.xcodeproj/xcshareddata/xcschemes/SNMPersistenceTests.xcscheme
  SniffMeet/SniffMeet.xcodeproj/xcshareddata/xcschemes/SniffMeet.xcscheme
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Interactor/ProfileCreateInteractor.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Presenter/ProfileCreatePresenter.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Router/ProfileCreateRouter.swift
  SniffMeet/SniffMeet/Source/Common/Helper/CGImageCoder.swift
  SniffMeet/SniffMeet/Source/Common/Helper/ImageSampler.swift
  SniffMeet/SniffMeet/Source/Home/EditProfile/Router/ProfileEditRoutable.swift
  SniffMeet/SniffMeet/Source/Home/EditProfile/View/ProfileEditViewController.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/Interactor/MateListInteractor.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/Presenter/MateListPresenter.swift
  SniffMeet/SniffMeet/Source/Mate/RequestMate/Router/RequestMateRouter.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/SaveProfileImageUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/SaveUserInfoUseCase.swift
  SniffMeet/TestPlan/SNMTestplan.xctestplan
  SniffMeet/TestPlan/SNMUtilityTestPlan.xctestplan
Labels: refactor, feature

#29 [ refactor] 리스트 페이지내이션 적용
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Common/Helper/Extension + Array.swift
  SniffMeet/SniffMeet/Source/Common/Helper/Extension + UIImage.swift
  SniffMeet/SniffMeet/Source/Common/Helper/Extension + UITableViewCell.swift
  SniffMeet/SniffMeet/Source/Common/Util/TaskSerialQueue.swift
  SniffMeet/SniffMeet/Source/Home/Alarm/Interactor/NotificationListInteractor.swift
  SniffMeet/SniffMeet/Source/Home/Alarm/Presenter/NotificationListPresenter.swift
  SniffMeet/SniffMeet/Source/Home/Alarm/View/NotificationListViewController.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/Interactor/MateListInteractor.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/Presenter/MateListPresenter.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/Router/MateListRouter.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/View/MateListViewController.swift
  SniffMeet/SniffMeet/Source/Supabase/Database/SupabaseDatabaseManager.swift
  SniffMeet/SniffMeet/Source/Supabase/Database/SupabaseDatabaseRequest.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestMateListUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestNotiListUseCase.swift
Labels: refactor, feature

#34 [fix] 디폴트 메이트 프로젝트가 아닌 Supabase단에서 처리하도록 수정
  SniffMeet/SniffMeet/Source/DTO/MateListDTO.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/CreateAccountUseCase.swift
Labels: refactor

#31 [test] MateListInteractor 테스트, RequestMateListUseCase 테스트
  SniffMeet/SNMSceneTests/MateListScene/MateListInteractorTests.swift
  SniffMeet/SNMSceneTests/MateListScene/MateListPresenterSpy.swift
  SniffMeet/SNMSceneTests/MateListScene/RemoteDatabaseManagerMock.swift
  SniffMeet/SNMSceneTests/MateListScene/UseCaseMock.swift
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet.xcodeproj/xcshareddata/xcschemes/SNMNetworkTests.xcscheme
  SniffMeet/SniffMeet.xcodeproj/xcshareddata/xcschemes/SNMPersistenceTests.xcscheme
  SniffMeet/SniffMeet.xcodeproj/xcshareddata/xcschemes/SniffMeet.xcscheme
  SniffMeet/SniffMeet/Source/Mate/MateList/Presenter/MateListPresenter.swift
  SniffMeet/SniffMeet/Source/OnBoarding/MainBoarding/Presenter/OnBoardingPresenter.swift
  SniffMeet/SniffMeet/Source/OnBoarding/MainBoarding/View/OnBoardingViewController.swift
  SniffMeet/TestPlan/SNMSceneTestPlan.xctestplan
Labels: test
